-- Create saved_tweets table
create table if not exists public.saved_tweets (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid not null references auth.users(id),
  created_at timestamptz default now()
);

-- Set up Row Level Security (RLS)
alter table public.saved_tweets enable row level security;

-- Create policies after table creation
do $$
begin
  -- Create policy to allow users to see only their own tweets
  execute format('create policy "Users can view their own tweets" on public.saved_tweets for select using (auth.uid() = user_id)');

  -- Create policy to allow users to insert their own tweets
  execute format('create policy "Users can insert their own tweets" on public.saved_tweets for insert with check (auth.uid() = user_id)');

  -- Create policy to allow users to update their own tweets
  execute format('create policy "Users can update their own tweets" on public.saved_tweets for update using (auth.uid() = user_id)');

  -- Create policy to allow users to delete their own tweets
  execute format('create policy "Users can delete their own tweets" on public.saved_tweets for delete using (auth.uid() = user_id)');
end $$; 